### ISSUE TITLE
`sly-asdf-load-system` doesn't trigger the debugger

### ISSUE THREAD

**Issue by aadcg** [mmgeorge/sly-asdf#42] opened 2022-11-02 09:37 UTC
I've noticed that issuing `(asdf:load-system :foo)` in the sly REPL isn't equivalent to issuing `(sly-asdf-load-system :foo)` since the latter doesn't trigger the debugger on compilation errors.

Am I missing something? Can I configure it? @Ambrevar 

Output on `(asdf:load-system :foo)`

```
CL-USER> (asdf:load-system :nyxt/gi-gtk)
; compiling file "/home/aadcg/common-lisp/nyxt/source/configuration.lisp" (written 01 NOV 2022 01:07:59 PM):
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     The symbol "*DEST-SOURCE-DIR*" is not external in the NYXT-ASDF package.
;   
;       Line: 97, Column: 35, File-Position: 3807
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/aadcg/common-lisp/nyxt/source/configuration.lisp" {100ABE2F63}>

; compilation aborted after 0:00:00.040
; Debugger entered on #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {100B47D433}>
```

Output on `(sly-asdf-load-system :foo)`

```
; 
; compilation unit aborted
;   caught 2 fatal ERROR conditions
;   caught 1 ERROR condition

; Evaluation aborted on #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {100B47D433}>
; compiling file "/home/aadcg/common-lisp/nyxt/source/configuration.lisp" (written 01 NOV 2022 01:07:59 PM):
; compilation aborted after 0:00:00.040
; 
; compilation unit aborted
;   caught 2 fatal ERROR conditions
```

**Comment by Ambrevar** [comment] 2022-11-02 10:13
I believe this is by design, so that SLY can try loading as many systems as it can and output a global report of the failed systems at the end.

**Comment by aadcg** [comment] 2022-11-02 15:17
That's a pity. 

I'll keep it open, as someone might have an insight.

**Comment by Ambrevar** [comment] 2022-11-03 09:22
Why is it a pity?  It's a nice feature in my opinion.  If you want to enable the debugger, calling `asdf:load-system` manually is very accessible too.

An option would be to add universal argument support (`C-u`), which would trigger the debugger.

**Comment by aadcg** [comment] 2022-11-03 09:35
I've always regarded this package as a nice utility to save some typing. But it turns out typing asdf commands and triggering `sly-asdf-*` isn't the same.

Perhaps the difference between these two is justified, but I didn't find why that is a good idea.

<strike>I'd suggest the opposite, add an universal argument not to trigger the debugger. Otherwise it trips users.</strike>

**Comment by aadcg** [comment] 2022-11-03 09:37
It seems that I missed this important bit of information. 

From the README:

> When using the built-in system load utlity, accessed via , + load-system from the repl, ASDF system compilation and load errors will be trapped and recorded as with other sly compilation errors, as opposed to dumping into the debugger like with calling asdf:load-system directly.

I just don't understand why this is a good idea.

**Comment by Ambrevar** [comment] 2022-11-03 10:39
Because in some cases you want to have a full report of the failures and not just stop at the first one.

**Comment by aadcg** [comment] 2022-11-03 13:08
@Ambrevar I see, thanks.

**Comment by mmgeorge** [comment] 2022-11-12 01:15
Yes, this is by design. Closing

**Closed as completed by mmgeorge** 2022-11-12 01:15 UTC
